### ISSUE TITLE
Library not working with OS X.

### ISSUE THREAD

**Issue by suchintan** [NicholasAStuart/myo-java#5]
Hi,

I tried using your library on OS X and it kept giving me the following errors:
````
java.lang.UnsatisfiedLinkError: no myo in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at com.thalmic.myo.Hub.copyAndLoadOSXFromTemp(Hub.java:123)
	at com.thalmic.myo.Hub.loadJniResources(Hub.java:60)
	at com.thalmic.myo.Hub.<init>(Hub.java:24)
	at com.thalmic.myo.example.HelloMyo.main(HelloMyo.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Unable to load myo64.dll from directory /var/folders/r2/6sjpbgvn24g9smp_25jxmhqc0000gn/T.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could Not Load myo and myo-java libs
	at com.thalmic.myo.Hub.loadJniResources(Hub.java:62)
	at com.thalmic.myo.Hub.<init>(Hub.java:24)
	at com.thalmic.myo.example.HelloMyo.main(HelloMyo.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
````
I dug a little deeper and found that the Hub.java class was going into the copyAndLoadOSXFromTemp method. Within this method, it was successfully copying the myo.framework and libmyo.jnilib files into java.library.path. 
I evaluated this by observing the directory structure during runtime using this:
````
String property = System.getProperty("java.library.path");
StringTokenizer parser = new StringTokenizer(property, ";");
File f = new File(parser.nextToken());
for(File fi : f.listFiles()){
     System.out.println(fi.getName());
}
````

But through all of that, it still gives the exception above.

Perhaps I'm doing something wrong or I missed a step? I'm relatively unfamiliar with System.getProperty to load properties, so I can't say for sure why it's failing to read the properties given.

**Comment by pawegio** [comment]
Same error on OS X 10.9.5:
```
Unable to load myo from system directories.
Unable to load libmyo.jnilib from directory /var/folders/8q/qcw3sl8j1ms2z0zk35d9k1th0000gn/T
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could Not Load myo and myo-java libs
	at com.thalmic.myo.Hub.loadJniResources(Hub.java:53)
	at com.thalmic.myo.Hub.<init>(Hub.java:23)
	at Main.main(Main.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by NicholasAStuart** [comment]
@pawegio Can you verify that the directory is getting copied over to that temp directory?

**Comment by pawegio** [comment]
Well, it is not copied...
Inside ```/var/folders/8q/qcw3sl8j1ms2z0zk35d9k1th0000gn/T``` I found only myo.framework

libmyo.jnilib was found only here:
![zrzut ekranu 2015-01-12 o 23 10 50](https://cloud.githubusercontent.com/assets/876573/5712176/599e172e-9ab0-11e4-88c7-f8f78c69bd3d.png)

**Comment by pawegio** [comment]
When I passed to VM options:
```-Djava.library.path="/Users/pawegio/Workspace/myo-java/src/main/resources/osx"```
I received:
```
java.lang.UnsatisfiedLinkError: /Users/pawegio/Workspace/myo-java/src/main/resources/osx/libmyo.jnilib: dlopen(/Users/pawegio/Workspace/myo-java/src/main/resources/osx/libmyo.jnilib, 1): Library not loaded: @rpath/myo.framework/Versions/A/myo
  Referenced from: /Users/pawegio/Workspace/myo-java/src/main/resources/osx/libmyo.jnilib
  Reason: no suitable image found.  Did find:
	/Users/pawegio/Workspace/myo-java/src/main/resources/osx/myo.framework/Versions/A/myo: code signature invalid for '/Users/pawegio/Workspace/myo-java/src/main/resources/osx/myo.framework/Versions/A/myo'
```

**Comment by NicholasAStuart** [comment]
@pawegio Can you try the newest version?

**Comment by MasterEjay** [comment]
I am getting the same error.

`Unable to load myo from system directories.
Unable to load libmyo.jnilib from directory /var/folders/vd/2nmp_9px2wgfdvmx9zxnl4_m0000gn/T
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could Not Load myo and myo-java libs
	at com.thalmic.myo.Hub.loadJniResources(Hub.java:53)
	at com.thalmic.myo.Hub.<init>(Hub.java:23)
	at com.thalmic.myo.example.HelloMyo.main(HelloMyo.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
`

Running OSX 10.10 Yosemite

**Comment by NicholasAStuart** [comment]
@MasterEjay  Unfortunately these are hard for me to diagnose. Can you try clearing out that temp directory, and ensuring that the directory is getting copied over? Are you using version 0.8.1?

**Comment by suchintan** [comment]
I got myo to work on OSX by using the Websocket layer (ws://127.0.0.1:10138/myo/3) along with the Java-Websocket library. For any of you that want to try it out, the docs are located here: https://developer.thalmic.com/forums/topic/534/

**Comment by NicholasAStuart** [comment]
I'm now seeing this on my machine. Apparently this is a problem with code signatures, I'm not sure if it's on the end of the myo library or my own. I'll continue to investigate this.

**Comment by NicholasAStuart** [comment]
@suchintan  @MasterEjay @pawegio @msalman86  

Please try to 0.8.2 version that is now available on Maven Central. It should fix the issues you all have been having. The issue was from the myo library not copying over correctly, and I believe I have solved this now.

**Comment by MKnierim** [comment]
Hey everyone,

has this been fixed definitely? I still encounter the error that the library could not be found. Working on OS X 10.11.6 using the latest version of the sdk, but no success... :(

Best regards
Michael
